---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
{{- if (eq .Values.global.env "staging" ) }}
    kubernetes.io/ingress.class: nginx-stage
{{- else }}
    kubernetes.io/ingress.class: nginx
{{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
spec:
  rules:
  - host: {{ pluck .Values.global.env .Values.app.main_domain | first | default .Values.app.main_domain._default }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              name: http
{{- if ne .Values.werf.env "local" }}
  - host: {{ pluck .Values.global.env .Values.app.profiler_domain | first | default .Values.app.profiler_domain._default }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              name: http-nginx
{{- end }}
  tls:
  - hosts:
      - {{ pluck .Values.global.env .Values.app.main_domain | first | default .Values.app.main_domain._default }}
{{- if ne .Values.werf.env "local" }}
      - {{ pluck .Values.global.env .Values.app.profiler_domain | first | default .Values.app.profiler_domain._default }}
{{- end }}
    secretName: {{ .Chart.Name }}-tls
{{- if ne .Values.werf.env "local" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-crt
spec:
  dnsNames:
  - {{ pluck .Values.global.env .Values.app.main_domain | first | default .Values.app.main_domain._default }}
  - {{ pluck .Values.global.env .Values.app.profiler_domain | first | default .Values.app.profiler_domain._default }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-yc
  secretName: {{ .Chart.Name }}-tls
{{- end }}